/**
 * src/notebooklm.ts
 *
 * NotebookLM Enterprise integration via Discovery Engine v1alpha API.
 * Creates/updates per-customer notebooks pre-loaded with Drive sources.
 *
 * FEATURE FLAG: This module is dormant unless NOTEBOOKLM_ENABLED=true in .env
 * AND the Discovery Engine API is enabled in the GCP project (BKL-AI10).
 * All operations fail gracefully — no crash if API is not enabled.
 *
 * Auth: reuses GEMINI_SERVICE_ACCOUNT_KEY (same service account as Vertex AI).
 * IAM role required: roles/discoveryengine.notebooklmAdmin on the GCP project.
 *
 * API docs: https://cloud.google.com/generative-ai-app-builder/docs/notebooklm-enterprise
 */

import { google } from 'googleapis'
import { makeAuth, GOOGLE_UNIFIED_TOKEN_PATH } from './google.ts'
import type { Customer } from './types.ts'

const GCP_PROJECT  = process.env.GOOGLE_CLOUD_PROJECT ?? 'jhorn-pai'
const GCP_LOCATION = 'us'  // NotebookLM Enterprise only available in 'us'
const API_BASE     = `https://discoveryengine.googleapis.com/v1alpha/projects/${GCP_PROJECT}/locations/${GCP_LOCATION}`

// Max sources per notebook (Discovery Engine v1alpha hard limit)
const MAX_SOURCES = 50

// ── Auth ──────────────────────────────────────────────────────────────────────

async function getAccessToken(): Promise<string> {
  const saKeyB64 = process.env.GEMINI_SERVICE_ACCOUNT_KEY
  if (saKeyB64) {
    const keyData = JSON.parse(Buffer.from(saKeyB64, 'base64').toString())
    const jwtAuth = new google.auth.JWT({
      email:  keyData.client_email,
      key:    keyData.private_key,
      scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    })
    const token = (await jwtAuth.getAccessToken()).token
    if (!token) throw new Error('[notebooklm] Failed to get access token from service account key')
    return token
  }
  const auth = makeAuth(GOOGLE_UNIFIED_TOKEN_PATH)
  const token = (await auth.getAccessToken()).token
  if (!token) throw new Error('[notebooklm] Failed to get access token — set GEMINI_SERVICE_ACCOUNT_KEY in .env')
  return token
}

// ── Types ─────────────────────────────────────────────────────────────────────

export interface NotebookResult {
  notebookId: string
  notebookUrl: string
  sourceCount: number
}

// ── API helpers ───────────────────────────────────────────────────────────────

async function apiRequest<T>(
  method: 'GET' | 'POST' | 'DELETE' | 'PATCH',
  path: string,
  body?: unknown,
): Promise<T> {
  const token = await getAccessToken()
  const res = await fetch(`${API_BASE}${path}`, {
    method,
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type':  'application/json',
      'x-goog-request-params': `project=${GCP_PROJECT}`,
    },
    body: body ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    const errText = await res.text().catch(() => res.statusText)
    throw new Error(`[notebooklm] API ${method} ${path} → ${res.status}: ${errText.slice(0, 300)}`)
  }
  return res.json() as Promise<T>
}

// ── Notebook CRUD ─────────────────────────────────────────────────────────────

interface NotebookListResponse {
  notebooks?: Array<{ name: string; displayName: string }>
}

interface NotebookCreateResponse {
  name: string
  displayName: string
}

interface SourceListResponse {
  corpora?: Array<{ name: string; spec?: { driveSource?: { resourceId: string } } }>
}

/**
 * Find an existing notebook by display name, or create a new one.
 * Returns the notebook's resource name (e.g. ".../notebooks/abc123").
 */
async function findOrCreateNotebook(displayName: string): Promise<string> {
  const list = await apiRequest<NotebookListResponse>('GET', '/notebooks?pageSize=100')
  const existing = list.notebooks?.find(n => n.displayName === displayName)
  if (existing) {
    console.log(`[notebooklm] found existing notebook: ${displayName}`)
    return existing.name
  }

  const created = await apiRequest<NotebookCreateResponse>('POST', '/notebooks', {
    displayName,
    description: `Auto-generated by DailyBriefDashboard — ${new Date().toISOString().slice(0, 10)}`,
  })
  console.log(`[notebooklm] created notebook: ${displayName} → ${created.name}`)
  return created.name
}

/**
 * Sync Drive file sources into a notebook.
 * Adds new sources, removes stale ones, respects 50-source limit (recency-first).
 */
async function syncSources(
  notebookName: string,
  driveFileIds: Array<{ id: string; name: string; modifiedTime?: string }>,
): Promise<number> {
  // Limit to MAX_SOURCES most recently modified files
  const sorted = [...driveFileIds].sort((a, b) => {
    const ta = a.modifiedTime ?? '0'
    const tb = b.modifiedTime ?? '0'
    return tb.localeCompare(ta)
  })
  const targetIds = sorted.slice(0, MAX_SOURCES).map(f => f.id)

  // Get current sources
  const existing = await apiRequest<SourceListResponse>('GET', `/${notebookName.split('/').pop()}/sources?pageSize=100`)
    .catch(() => ({ corpora: [] }))
  const existingIds = new Set(
    (existing.corpora ?? []).map(c => c.spec?.driveSource?.resourceId).filter(Boolean) as string[]
  )

  // Add new sources (not already in notebook)
  const toAdd = targetIds.filter(id => !existingIds.has(id))
  if (toAdd.length > 0) {
    await apiRequest('POST', `/notebooks/${notebookName.split('/').pop()}/sources:batchCreate`, {
      requests: toAdd.map(id => ({
        source: {
          spec: {
            driveSource: { resourceId: id },
          },
        },
      })),
    }).catch((e: any) => {
      console.warn(`[notebooklm] batchCreate failed: ${e.message}`)
    })
    console.log(`[notebooklm] added ${toAdd.length} sources to ${notebookName}`)
  }

  // Remove stale sources (in notebook but not in current target set)
  const targetSet = new Set(targetIds)
  const toRemove = (existing.corpora ?? []).filter(
    c => c.spec?.driveSource?.resourceId && !targetSet.has(c.spec.driveSource.resourceId)
  )
  for (const corpus of toRemove) {
    const sourceId = corpus.name?.split('/').pop()
    if (sourceId) {
      await apiRequest('DELETE', `/notebooks/${notebookName.split('/').pop()}/sources/${sourceId}`)
        .catch((e: any) => console.warn(`[notebooklm] remove source failed: ${e.message}`))
    }
  }
  if (toRemove.length > 0) {
    console.log(`[notebooklm] removed ${toRemove.length} stale sources from ${notebookName}`)
  }

  return targetIds.length
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Create or update a NotebookLM notebook for a customer.
 * Sources are populated from the customer's Google Drive folder.
 * Returns notebook ID and URL for storage in customers.json.
 *
 * @param customer     Customer object (needs driveFolderId or notebookId)
 * @param driveFileIds Drive file list from the customer folder
 */
export async function createOrUpdateNotebook(
  customer: Customer,
  driveFileIds: Array<{ id: string; name: string; modifiedTime?: string }>,
): Promise<NotebookResult> {
  if (!process.env.NOTEBOOKLM_ENABLED) {
    throw new Error('[notebooklm] NOTEBOOKLM_ENABLED not set — enable in .env to use this feature')
  }

  const displayName = `DailyBrief — ${customer.name}`
  const notebookName = await findOrCreateNotebook(displayName)
  const notebookId = notebookName.split('/').pop()!
  const notebookUrl = `https://notebooklm.google.com/notebook/${notebookId}`

  const sourceCount = await syncSources(notebookName, driveFileIds)

  console.log(`[notebooklm] ${customer.name}: notebook ready — ${sourceCount} sources, ${notebookUrl}`)
  return { notebookId, notebookUrl, sourceCount }
}

/**
 * Check if NotebookLM integration is configured and ready.
 * Does NOT make API calls — only checks env config.
 */
export function isNotebookLmEnabled(): boolean {
  return process.env.NOTEBOOKLM_ENABLED === 'true' &&
    (!!process.env.GEMINI_SERVICE_ACCOUNT_KEY || false)
}
